version: '3'

services:
  nginx:
    image: nginx:1.25.4-alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - php-fpm
    restart: on-failure

  php-fpm:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www
    restart: on-failure

  mysql:
    image: mysql:5.7
    build:
      context: ./docker/mySql
    restart: always     #каждый раз будет по-новому создаватса
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
